### ISSUE TITLE
Unable to build VST2 plugin

### ISSUE THREAD

**Issue by LJ1102** [vsariola/sointu#96] opened 2023-08-09 02:52 UTC
Tried to build the VST2 plugin using the command line from the readme and getting the following output:
```
C:\Users\lj110\Desktop\sointu-master>go build -buildmode=c-shared -tags=plugin -o sointu-vsti.dll .\cmd\sointu-vsti\
# github.com/vsariola/sointu/cmd/sointu-vsti
cmd\sointu-vsti\main.go:13:16: undefined: vst2.MIDIEvent
cmd\sointu-vsti\main.go:18:14: undefined: vst2.MIDIEvent
cmd\sointu-vsti\main.go:50:7: undefined: vst2.PluginAllocator
cmd\sointu-vsti\main.go:50:49: undefined: vst2.Plugin
cmd\sointu-vsti\main.go:50:62: undefined: vst2.Dispatcher
cmd\sointu-vsti\main.go:58:45: undefined: vst2.MIDIEvent
cmd\sointu-vsti\main.go:60:15: undefined: vst2.Plugin
cmd\sointu-vsti\main.go:69:41: undefined: vst2.FloatBuffer
cmd\sointu-vsti\main.go:82:12: undefined: vst2.Dispatcher
cmd\sointu-vsti\main.go:90:38: undefined: vst2.EventsPtr
cmd\sointu-vsti\main.go:90:38: too many errors
```
installed the VST2 thing(https://github.com/pipelined/vst2) using `go get -u pipelined.dev/audio/vst2` and rerunning the build, same output.

Building the standalone tracker using `go build -o sointu-track.exe cmd/sointu-track/main.go` worked just fine, except that the GM samples are not playing on my system (Windows 10).

**Comment by vsariola** [comment] 2023-08-09 07:32
Not able to reproduce. I checked out a fresh repo and copy-pasted your command to console & it passes without errors (Windows 10).

What version of go you have? I'm on 1.20.2 windows/amd64.

The latest Windows binaries, including vsti & native-vsti, can also be downloaded from here too: https://github.com/vsariola/sointu/suites/14455682343/artifacts/816237188

They are always built as part of actions.

**Comment by vsariola** [comment] 2023-08-09 07:38
And samples do not work on the "non-native" version of the tracker/vsti; it has to be the native version. Someday, I'll fix this, but this is issue #75.

**Comment by LeStahL** [comment] 2023-08-27 08:03
I have the problem as well (on Windows). The commands above do not solve it. Will investigate a little

**Comment by vsariola** [comment] 2023-08-27 11:21
We have found a solution to this: setting environment variable `CGO_ENABLED` to 1 fixes the problem.

Then it still might give an error about missing compiler, but installing cgo compatible compiler e.g. [gcc](https://gcc.gnu.org/) should do the trick. On windows, you best bet is [MinGW](http://www.mingw.org/), e.g. from [tdm-gcc](https://jmeubank.github.io/tdm-gcc/).

**Comment by vsariola** [comment] 2023-08-27 11:55
I have updated the README.md to reflect the need for the environment variable CGO_ENABLED=1, closing this for now

**Closed by vsariola** 2023-08-27 11:55 UTC
Labels: bug

**Comment by vsariola** [comment] 2023-08-28 10:30
Clarification: the root cause of this is that cgo compatible compiler e.g. gcc is missing, along with a CC environment variable pointing to that compiler. Golang tries to find the C-compiler, but being unable to find it, automatically considers CGO_ENABLED=0. When this happens, all files that include C-code are just excluded from the build, resulting in missing types.

Forcing CGO_ENABLED=1 is a good idea, as it gives better error messages of the root cause (missing compiler).

Relevant documentation: https://pkg.go.dev/cmd/cgo

The crucial paragraph:

> The cgo tool is enabled by default for native builds on systems where it is expected to work. It is disabled by default when cross-compiling as well as when the CC environment variable is unset and the default C compiler (typically gcc or clang) cannot be found on the system PATH. You can override the default by setting the CGO_ENABLED environment variable when running the go tool: set it to 1 to enable the use of cgo, and to 0 to disable it. The go tool will set the build constraint "cgo" if cgo is enabled. The special import "C" implies the "cgo" build constraint, as though the file also said "//go:build cgo". Therefore, if cgo is disabled, files that import "C" will not be built by the go tool. (For more about build constraints see https://golang.org/pkg/go/build/#hdr-Build_Constraints).
