### ISSUE TITLE
Added noise element during playback, outaux is now red, playback stopped and refuses to restart

### ISSUE THREAD

**Issue by esaruoho** [vsariola/sointu#22] opened 2021-02-15 10:33 UTC
I had pressed (+) and left the "---" there.
I pressed space to start playback.
Loaded "noise" into ---.
Playback stopped, and outaux turned red. playback seems to not work anymore.

<img width="249" alt="Screenshot 2021-02-15 at 12 32 41" src="https://user-images.githubusercontent.com/4966687/107935344-f1087c80-6f89-11eb-817a-1f87d837e3fa.png">

**Comment by vsariola** [comment] 2021-02-16 20:59
This is by design: noise is a signal source and every signal source needs to have equal number. This is essentially the same issue as #32: the patch does not compile. I'm closing this as a duplicate of #32; please comment there what you think is the best solution.

The red color is a hint that the patch is no good, but more prominent error message might help. Although the error message better be good; "stack not balanced" probably is probably not very helpful, but that's probably what we now get if we just show what error message the functions return.

**Closed by vsariola** 2021-02-16 20:59 UTC
